/***********************************************************************/
/*                                                                     */
/*  FILE        :intprg.c                                              */
/*  DATE        :Mon, Jul 22, 2019                                     */
/*  DESCRIPTION :Interrupt Program                                     */
/*  CPU TYPE    :H8SX/1544                                             */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


#include <machine.h>
#pragma section IntPRG
// vector 1 Reserved

// vector 2 Reserved

// vector 3 Reserved

// vector 4 Illegal code
__interrupt(vect=4) void INT_Illegal_code(void){/* sleep(); */}
// vector 5 Trace
__interrupt(vect=5) void INT_Trace(void){/* sleep(); */}
// vector 6 Reserved

// vector 7 NMI
__interrupt(vect=7) void INT_NMI(void){/* sleep(); */}
// vector 8 trap #0
__interrupt(vect=8) void INT_TRAP0(void){/* sleep(); */}
// vector 9 trap #1
__interrupt(vect=9) void INT_TRAP1(void){/* sleep(); */}
// vector 10 trap #2
__interrupt(vect=10) void INT_TRAP2(void){/* sleep(); */}
// vector 11 trap #3
__interrupt(vect=11) void INT_TRAP3(void){/* sleep(); */}
// vector 12 CPU Address error
__interrupt(vect=12) void INT_CPU_Address(void){/* sleep(); */}
// vector 13 DMA Address error
__interrupt(vect=13) void INT_DMA_Address(void){/* sleep(); */}
// vector 14 Reserved

// vector 15 Reserved

// vector 16 Reserved

// vector 17 Reserved

// vector 18 Reserved

// vector 19 Reserved

// vector 20 Reserved

// vector 21 Reserved

// vector 22 Reserved

// vector 23 Reserved

// vector 24 Reserved

// vector 25 Reserved

// vector 26 Reserved

// vector 27 Reserved

// vector 28 Reserved

// vector 29 Reserved

// vector 30 Reserved

// vector 31 Reserved

// vector 32 Reserved

// vector 33 Reserved

// vector 34 Reserved

// vector 35 Reserved

// vector 36 Reserved

// vector 37 Reserved

// vector 38 Reserved

// vector 39 Reserved

// vector 40 Reserved

// vector 41 Reserved

// vector 42 Reserved

// vector 43 Reserved

// vector 44 Reserved

// vector 45 Reserved

// vector 46 Reserved

// vector 47 Reserved

// vector 48 Reserved

// vector 49 Reserved

// vector 50 Reserved

// vector 51 Reserved

// vector 52 Reserved

// vector 53 Reserved

// vector 54 Reserved

// vector 55 Reserved

// vector 56 Reserved

// vector 57 Reserved

// vector 58 Reserved

// vector 59 Reserved

// vector 60 Reserved

// vector 61 Reserved

// vector 62 Reserved

// vector 63 Reserved

// vector 64 External trap IRQ0
__interrupt(vect=64) void INT_IRQ0(void){/* sleep(); */}
// vector 65 External trap IRQ1
__interrupt(vect=65) void INT_IRQ1(void){/* sleep(); */}
// vector 66 External trap IRQ2
__interrupt(vect=66) void INT_IRQ2(void){/* sleep(); */}
// vector 67 External trap IRQ3
__interrupt(vect=67) void INT_IRQ3(void){/* sleep(); */}
// vector 68 External trap IRQ4
__interrupt(vect=68) void INT_IRQ4(void){/* sleep(); */}
// vector 69 External trap IRQ5
__interrupt(vect=69) void INT_IRQ5(void){/* sleep(); */}
// vector 70 External trap IRQ6
__interrupt(vect=70) void INT_IRQ6(void){/* sleep(); */}
// vector 71 External trap IRQ7
__interrupt(vect=71) void INT_IRQ7(void){/* sleep(); */}
// vector 72 External trap IRQ8
__interrupt(vect=72) void INT_IRQ8(void){/* sleep(); */}
// vector 73 External trap IRQ9
__interrupt(vect=73) void INT_IRQ9(void){/* sleep(); */}
// vector 74 External trap IRQ10
__interrupt(vect=74) void INT_IRQ10(void){/* sleep(); */}
// vector 75 External trap IRQ11
__interrupt(vect=75) void INT_IRQ11(void){/* sleep(); */}
// vector 76 External trap IRQ12
__interrupt(vect=76) void INT_IRQ12(void){/* sleep(); */}
// vector 77 External trap IRQ13
__interrupt(vect=77) void INT_IRQ13(void){/* sleep(); */}
// vector 78 External trap IRQ14
__interrupt(vect=78) void INT_IRQ14(void){/* sleep(); */}
// vector 79 External trap IRQ15
__interrupt(vect=79) void INT_IRQ15(void){/* sleep(); */}
// vector 80 Reserved

// vector 81 WOVI
__interrupt(vect=81) void INT_WOVI(void){/* sleep(); */}
// vector 82 Reserved

// vector 83 Reserved

// vector 84 Reserved

// vector 85 Reserved

// vector 86 ADI0
__interrupt(vect=86) void INT_ADI0(void){/* sleep(); */}
// vector 87 ADI1
__interrupt(vect=87) void INT_ADI1(void){/* sleep(); */}
// vector 88 TGI0A TPU0
// __interrupt(vect=88) void INT_TGI0A_TPU0(void){/* sleep(); */}
// vector 89 TGI0B TPU0
__interrupt(vect=89) void INT_TGI0B_TPU0(void){/* sleep(); */}
// vector 90 TGI0C TPU0
__interrupt(vect=90) void INT_TGI0C_TPU0(void){/* sleep(); */}
// vector 91 TGI0D TPU0
__interrupt(vect=91) void INT_TGI0D_TPU0(void){/* sleep(); */}
// vector 92 TCI0V TPU0
__interrupt(vect=92) void INT_TCI0V_TPU0(void){/* sleep(); */}
// vector 93 TGI1A TPU1
// __interrupt(vect=93) void INT_TGI1A_TPU1(void){/* sleep(); */}
// vector 94 TGI1B TPU1
__interrupt(vect=94) void INT_TGI1B_TPU1(void){/* sleep(); */}
// vector 95 TCI1V TPU1
__interrupt(vect=95) void INT_TCI1V_TPU1(void){/* sleep(); */}
// vector 96 TCI1U TPU1
__interrupt(vect=96) void INT_TCI1U_TPU1(void){/* sleep(); */}
// vector 97 TGI2A TPU2
__interrupt(vect=97) void INT_TGI2A_TPU2(void){/* sleep(); */}
// vector 98 TGI2B TPU2
__interrupt(vect=98) void INT_TGI2B_TPU2(void){/* sleep(); */}
// vector 99 TCI2V TPU2
__interrupt(vect=99) void INT_TCI2V_TPU2(void){/* sleep(); */}
// vector 100 TCI2U TPU2
__interrupt(vect=100) void INT_TCI2U_TPU2(void){/* sleep(); */}
// vector 101 TGI3A TPU3
// __interrupt(vect=101) void INT_TGI3A_TPU3(void){/* sleep(); */}
// vector 102 TGI3B TPU3
__interrupt(vect=102) void INT_TGI3B_TPU3(void){/* sleep(); */}
// vector 103 TGI3C TPU3
__interrupt(vect=103) void INT_TGI3C_TPU3(void){/* sleep(); */}
// vector 104 TGI3D TPU3
__interrupt(vect=104) void INT_TGI3D_TPU3(void){/* sleep(); */}
// vector 105 TCI3V TPU3
__interrupt(vect=105) void INT_TCI3V_TPU3(void){/* sleep(); */}
// vector 106 TGI4A TPU4
// __interrupt(vect=106) void INT_TGI4A_TPU4(void){/* sleep(); */}
// vector 107 TGI4B TPU4
__interrupt(vect=107) void INT_TGI4B_TPU4(void){/* sleep(); */}
// vector 108 TCI4V TPU4
__interrupt(vect=108) void INT_TCI4V_TPU4(void){/* sleep(); */}
// vector 109 TCI4U TPU4
__interrupt(vect=109) void INT_TCI4U_TPU4(void){/* sleep(); */}
// vector 110 TGI5A TPU5
// __interrupt(vect=110) void INT_TGI5A_TPU5(void){/* sleep(); */}
// vector 111 TGI5B TPU5
__interrupt(vect=111) void INT_TGI5B_TPU5(void){/* sleep(); */}
// vector 112 TCI5V TPU5
__interrupt(vect=112) void INT_TCI5V_TPU5(void){/* sleep(); */}
// vector 113 TCI5U TPU5
__interrupt(vect=113) void INT_TCI5U_TPU5(void){/* sleep(); */}
// vector 114 Reserved

// vector 115 Reserved

// vector 116 Reserved

// vector 117 Reserved

// vector 118 Reserved

// vector 119 Reserved

// vector 120 Reserved

// vector 121 Reserved

// vector 122 Reserved

// vector 123 Reserved

// vector 124 Reserved

// vector 125 Reserved

// vector 126 Reserved

// vector 127 Reserved

// vector 128 TEND0 DMAC
__interrupt(vect=128) void INT_TEND0_DMAC(void){/* sleep(); */}
// vector 129 TEND1 DMAC
__interrupt(vect=129) void INT_TEND1_DMAC(void){/* sleep(); */}
// vector 130 TEND2 DMAC
__interrupt(vect=130) void INT_TEND2_DMAC(void){/* sleep(); */}
// vector 131 TEND3 DMAC
__interrupt(vect=131) void INT_TEND3_DMAC(void){/* sleep(); */}
// vector 132 Reserved

// vector 133 Reserved

// vector 134 Reserved

// vector 135 Reserved

// vector 136 EEND0 DMAC
__interrupt(vect=136) void INT_EEND0_DMAC(void){/* sleep(); */}
// vector 137 EEND1 DMAC
__interrupt(vect=137) void INT_EEND1_DMAC(void){/* sleep(); */}
// vector 138 EEND2 DMAC
__interrupt(vect=138) void INT_EEND2_DMAC(void){/* sleep(); */}
// vector 139 EEND3 DMAC
__interrupt(vect=139) void INT_EEND3_DMAC(void){/* sleep(); */}
// vector 140 Reserved

// vector 141 Reserved

// vector 142 Reserved

// vector 143 Reserved

// vector 144 ERI0 SCI0
// __interrupt(vect=144) void INT_ERI0_SCI0(void){/* sleep(); */}
// vector 145 RXI0 SCI0
// __interrupt(vect=145) void INT_RXI0_SCI0(void){/* sleep(); */}
// vector 146 TXI0 SCI0
__interrupt(vect=146) void INT_TXI0_SCI0(void){/* sleep(); */}
// vector 147 TEI0 SCI0
__interrupt(vect=147) void INT_TEI0_SCI0(void){/* sleep(); */}
// vector 148 Reserved

// vector 149 Reserved

// vector 150 Reserved

// vector 151 Reserved

// vector 152 ERI2 SCI2
// __interrupt(vect=152) void INT_ERI2_SCI2(void){/* sleep(); */}
// vector 153 RXI2 SCI2
// __interrupt(vect=153) void INT_RXI2_SCI2(void){/* sleep(); */}
// vector 154 TXI2 SCI2
__interrupt(vect=154) void INT_TXI2_SCI2(void){/* sleep(); */}
// vector 155 TEI2 SCI2
__interrupt(vect=155) void INT_TEI2_SCI2(void){/* sleep(); */}
// vector 156 Reserved

// vector 157 Reserved

// vector 158 Reserved

// vector 159 Reserved

// vector 160 ERI4 SCI4
// __interrupt(vect=160) void INT_ERI4_SCI4(void){/* sleep(); */}
// vector 161 RXI4 SCI4
// __interrupt(vect=161) void INT_RXI4_SCI4(void){/* sleep(); */}
// vector 162 TXI4 SCI4
__interrupt(vect=162) void INT_TXI4_SCI4(void){/* sleep(); */}
// vector 163 TEI4 SCI4
__interrupt(vect=163) void INT_TEI4_SCI4(void){/* sleep(); */}
// vector 164 Reserved

// vector 165 Reserved

// vector 166 Reserved

// vector 167 Reserved

// vector 168 Reserved

// vector 169 Reserved

// vector 170 Reserved

// vector 171 Reserved

// vector 172 Reserved

// vector 173 Reserved

// vector 174 Reserved

// vector 175 Reserved

// vector 176 Reserved

// vector 177 Reserved

// vector 178 Reserved

// vector 179 Reserved

// vector 180 Reserved

// vector 181 Reserved

// vector 182 Reserved

// vector 183 Reserved

// vector 184 Reserved

// vector 185 Reserved

// vector 186 Reserved

// vector 187 Reserved

// vector 188 Reserved

// vector 189 Reserved

// vector 190 Reserved

// vector 191 Reserved

// vector 192 Reserved

// vector 193 Reserved

// vector 194 Reserved

// vector 195 Reserved

// vector 196 Reserved

// vector 197 Reserved

// vector 198 Reserved

// vector 199 Reserved

// vector 200 Reserved

// vector 201 Reserved

// vector 202 Reserved

// vector 203 Reserved

// vector 204 Reserved

// vector 205 Reserved

// vector 206 Reserved

// vector 207 Reserved

// vector 208 Reserved

// vector 209 Reserved

// vector 210 Reserved

// vector 211 Reserved

// vector 212 Reserved

// vector 213 Reserved

// vector 214 Reserved

// vector 215 Reserved

// vector 216 IICI0 IIC2
__interrupt(vect=216) void INT_IICI0_IIC2(void){/* sleep(); */}
// vector 217 Reserved

// vector 218 IICI1 IIC2
__interrupt(vect=218) void INT_IICI1_IIC2(void){/* sleep(); */}
// vector 219 Reserved

// vector 220 RM0 RCAN
__interrupt(vect=220) void INT_RM0_RCAN(void){/* sleep(); */}
// vector 221 RM1 RCAN
__interrupt(vect=221) void INT_RM1_RCAN(void){/* sleep(); */}
// vector 222 ERS0/OVR0 HCAN
// __interrupt(vect=222) void INT_ERSOVR0_HCAN(void){/* sleep(); */}
// vector 223 ERS1/OVR1 HCAN
__interrupt(vect=223) void INT_ERSOVR1_HCAN(void){/* sleep(); */}
// vector 224 CMI0 MCPWM0
__interrupt(vect=224) void INT_CMI0_MCPWM0(void){/* sleep(); */}
// vector 225 CMI1 MCPWM1
__interrupt(vect=225) void INT_CMI1_MCPWM1(void){/* sleep(); */}
// vector 226 WCMI WAT
__interrupt(vect=226) void INT_WCMI_WAT(void){/* sleep(); */}
// vector 227 Reserved

// vector 228 CMI0 PWM0
__interrupt(vect=228) void INT_CMI0_PWM0(void){/* sleep(); */}
// vector 229 CMI1 PWM1
__interrupt(vect=229) void INT_CMI1_PWM1(void){/* sleep(); */}
// vector 230 CMI2 PWM2
__interrupt(vect=230) void INT_CMI2_PWM2(void){/* sleep(); */}
// vector 231 Reserved

// vector 232 SGI SDG0
__interrupt(vect=232) void INT_SGI_SDG0(void){/* sleep(); */}
// vector 233 SGI SDG1
__interrupt(vect=233) void INT_SGI_SDG1(void){/* sleep(); */}
// vector 234 SSERI0/SSRXI0/SSTXI0 SSU0
__interrupt(vect=234) void INT_SSU0(void){/* sleep(); */}
// vector 235 SSERI1/SSRXI1/SSTXI1 SSU1
__interrupt(vect=235) void INT_SSU1(void){/* sleep(); */}
// vector 236 SGI SDG2
__interrupt(vect=236) void INT_SGI_SDG2(void){/* sleep(); */}
// vector 237 SGI SDG3
__interrupt(vect=237) void INT_SGI_SDG3(void){/* sleep(); */}
// vector 238 WCMI(SW-STBY) WAT
__interrupt(vect=238) void INT_WCMIS_WAT(void){/* sleep(); */}
// vector 239 Reserved

// vector 240 Reserved

// vector 241 Reserved

// vector 242 Reserved

// vector 243 Reserved

// vector 244 Reserved

// vector 245 Reserved

// vector 246 Reserved

// vector 247 Reserved

// vector 248 Reserved

// vector 249 Reserved

// vector 250 Reserved

// vector 251 Reserved

// vector 252 Reserved

// vector 253 Reserved

// vector 254 Reserved

// vector 255 Reserved

