/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Mon, Jul 22, 2019                                     */
/*  DESCRIPTION :Aliases of Integer Type                               */
/*  CPU TYPE    :H8SX/1544                                             */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  

#ifndef	_TYPEDEFINE_HEADER__
#define _TYPEDEFINE_HEADER__

typedef	  signed	char	CHAR;		// 8 bit   signed character
typedef	  signed	char	INT8S;
typedef	  signed	char	SBYTE;
typedef	  signed	char	_SBYTE;

typedef unsigned	char	BYTE;		// 8 bit unsigned character
typedef	unsigned	char	INT8U;
typedef unsigned	char	UCHAR;
typedef	unsigned	char	PBYTE;
typedef	unsigned	char	BOOL;
typedef unsigned	char	_UBYTE;

typedef	  signed	short	SHORT;		// 16 bit   signed integer
typedef	  signed	short	INT16S;
typedef	  signed	short	SWORD;
typedef   signed	short	_SWORD;

typedef unsigned	short	WORD;		// 16 bit unsigned integer
typedef	unsigned	short	INT16U;
typedef unsigned	short	USHORT;
typedef unsigned	short	_UWORD;

typedef	  signed	int		INT;		// 32 bit   signed integer
typedef   signed	int		_SINT;

typedef	unsigned	int		UINT;		// 32 bit unsigned integer
typedef unsigned	int		_UINT;

typedef	  signed 	long	LONG;		// 32 bit   signed integer
typedef	  signed	long	INT32S;
typedef   signed	long	_SDWORD;

typedef unsigned	long	ULONG;		// 32 bit unsigned integer
typedef	unsigned	long	INT32U;
typedef unsigned	long	DWORD;
typedef unsigned	long	_UDWORD;

typedef				float	FLOAT;		// 32 bit floating point
typedef				float	FP32;

typedef				double	DOUBLE;		// 64 bit floating point
typedef				double	FP64;
/////////////////////////////////////////////////////////////////////////


/***********************************************************************/
/* edited By : sslim
/***********************************************************************/
#define NOT_EXIST	99	


typedef enum
{
	OFF = 0,
	ON = 1
} power_t;

typedef enum
{
	false = 0,
	true = 1
} bool_t;

typedef enum
{
	LOW = 0,
	HIGH = 1
} swithc_t;

typedef enum
{
	NO = 0,
	YES = 1
};

typedef enum
{ 
	STEP0, STEP1, STEP2, STEP3, STEP4, STEP5, STEP6, STEP7, STEP8, STEP9, STEP10, 
	STEP11, STEP12, STEP13, STEP14, STEP15, STEP16, STEP17, STEP18, STEP19, STEP20,
} step_t;

typedef enum
{ 
	SUB0, SUB1, SUB2, SUB3, SUB4, SUB5, SUB6, SUB7, SUB8, SUB9,
	SUB10, SUB11, 
} sub_t;

typedef enum
{ 
	SUB_STEP0, SUB_STEP1, SUB_STEP2, SUB_STEP3, SUB_STEP4, SUB_STEP5, SUB_STEP6, 
	SUB_STEP7, SUB_STEP8, SUB_STEP9, SUB_STEP10, SUB_STEP11, SUB_STEP12, SUB_STEP13, 
	SUB_STEP14, SUB_STEP15, SUB_STEP16, SUB_STEP17, SUB_STEP18,
} subStep_t;


#endif	/*_TYPEDEFINE_HEADER__*/